### ISSUE TITLE
Security: TLS Support

### ISSUE THREAD

**Issue by noodlefrenzy** [noodlefrenzy/node-amqp-1-0#17]
Must support TLS negotiation prior to connection handshake.  Req'd for EventHub.

**Comment by amenzhinsky** [comment]
Why was this closed?
http://docs.oasis-open.org/amqp/core/v1.0/amqp-core-security-v1.0.html
> 5.2 TLS
>
> To establish a TLS session, each peer MUST start by sending a protocol header before commencing with TLS negotiation. The protocol header consists of the upper case ASCII letters "AMQP" followed by a protocol id of two, followed by three unsigned bytes representing the major, minor, and revision of the specification version (currently 1 (TLS-MAJOR), 0 (TLS-MINOR), 0 (TLS-REVISION)). In total this is an 8-octet sequence:
