### ISSUE TITLE
Failover support?

### ISSUE THREAD

**Issue by ps2goat** [noodlefrenzy/node-amqp-1-0#370]
For ActiveMQ, in the Java world, there is the idea of a failover connection.  Is there support for this in this library?  With AmazonMQ, we have two possible instances to connect to, and either one can be up at any given time (but only one will be available).

Also, the library just hangs when trying to connect with a bad connection, rather than throwing an error and letting the process continue.

**Comment by amarzavery** [comment]
This library is not being actively maintained. There would be no bug fixes or new features. I would recommend using https://github.com/amqp/rhea
