### ISSUE TITLE
Receiver stops dequeueing messages in case of big queue length

### ISSUE THREAD

**Issue by ltozi** [noodlefrenzy/node-amqp-1-0#44]
It seems that receiver stops its receive activity when a lot of messages are pending inside queue. I noticed this during stress test, sending a message per second.

Is this probably the expected behavior when the amqp client detects possible memory leak?

**Comment by noodlefrenzy** [comment]
No, I'll check into it - I'd seen it stop temporarily as the server delays sending additional messages, but I hadn't seen it stop entirely.  It could be an issue with me sending subsequent "Flow" frames to keep up the traffic when under duress.

**Comment by ltozi** [comment]
This is an error found inside logs during our stress test. After some load (a message per second) it seems that receiver stops its activity:

{ descriptor: [Int64 value:29 octets:00 00 00 00 00 00 00 1d],
      value: undefined,
      condition: { contents: 'amqp:link:detach-forced' },
      description: 'The link \'2818003:mqtt_publish_dev_RX\' is force detached by the broker due to errors occurred in consumer(link4709). Detach origin: AmqpMessageConsumer.Fault. TrackingId:13fca8ed00003c6a0000126554da0f06_G10_B12,TimeStamp:2/10/2015 2:10:38 PM', errorInfo: null }

**Comment by noodlefrenzy** [comment]
I found one issue, where it looks like I might have misunderstood the spec (it says "link-credit: the current maximum number of messages that can be received", and I assumed this is the _current_ link credit, and not the _maximum over all time_ link credit).  Anyway, looks like the EventHub folks interpreted that differently, so as soon as I sent a flow frame with link-credit == _the number of messages they'd already sent_, they stopped sending.  

That doesn't explain the detach, though, just the lack of messages after a period.  So I'm running a stress right now to see if I can replicate that.

I'll have a new release out soon, at which time I'll update this bug and close it.

**Comment by noodlefrenzy** [comment]
Hey, so I just pushed 0.0.12 - I successfully ran through 10k sends at 2/sec, with all successfully received - all via EventHub.

Closing this, but _please_ reopen and let me know if you still have issues.  I'm following up with the EventHub team on at least one issue I was seeing with them.

I'm also starting a similar test with ServiceBus queues shortly to ensure it resolves any similar issues with them.  I'll reopen this myself if I see problems from that test.

Thanks again for your patience!
-Mike

**Comment by noodlefrenzy** [comment]
I'm up to 5000 messages without a problem - my guess was I was hitting the same issue as with EventHub, and then the link just timed out.

**Comment by ltozi** [comment]
Nice job! I run the test again with the latest version and the problem is gone.

Thanks,
Luigi

**Comment by noodlefrenzy** [comment]
Fantastic!  Glad to hear it!  As always, let me know if you run into any other issues, and thanks for being patient with me :)
