### ISSUE TITLE
Is node-amqp-1-0 supports the exchanging of messages from Jboss Active MQ topic?

### ISSUE THREAD

**Issue by hverma11** [noodlefrenzy/node-amqp-1-0#46]
I am planning to implement the pub/sub messaging framework from client to Services via Jboss Active MQ. 
Before heading to use topics for exchanging the messages , I just want to know the compatibility of Topics with node-amq-1-0. I already tried with queue , it is working fine but wants Topic now.

Please share the inputs.

**Comment by noodlefrenzy** [comment]
I haven't used JBoss AMQ's Topics before, and not with this library, but I've used the Topics within Azure ServiceBus without a problem.  If you have any issues, please don't hesitate to open a bug.  If you're not starting for a while, I might have a chance to try it out myself early next week, but I'm slammed with other work today, sorry.

**Comment by hverma11** [comment]
Hi, I tried using the topics but it always create the producers and consumers under queue in JBoss ActiveMQ.

Can you please have alook and confirm the exact usage ?

**Comment by noodlefrenzy** [comment]
It may take me a bit - I'm out of the country this week, but I'll look as soon as I get back.

**Comment by hverma11** [comment]
Hi noodlefrenzy,

 Hope you are back. Did you get chance to look into the above mentioned issue.

**Comment by mbroadst** [comment]
@noodlefrenzy I think this can be closed as well, I've answered the question on @hverma11 's other issue, and can confirm that the library does indeed work with topics in ActiveMQ

**Comment by noodlefrenzy** [comment]
Thanks for verifying.  Closing.
