### ISSUE TITLE
Not able to parse the response in receive

### ISSUE THREAD

**Issue by hverma11** [noodlefrenzy/node-amqp-1-0#47]
I can see my payload in the queue @ JBoss Active MQ i.e.
bytes:
5b 7b 22 69 64 22 3a 31 2c 22 74 69 74 6c 65 22 3a 22 74 69 74 6c 65 22 2c 22 63 72 65 64 69 74 73 22 3a 33 33 2c 22 63 6f 6e 74 65 6e 74 22 3a 22 6a 74 79 6a 22 2c 22 6c 65 76 65 6c 73 22 3a 31 2c 22 71 75 61 6c 69 66 69 63 61 74 69 6f 6e 54 79 70 65 22 3a 31 2c 22 65 6e 74 72 79 52 65 71 75 69 72 65 6d 65 6e 74 73 22 3a 22 6a 79 74 6a 22 2c 22 63 72 65 61 74 65 44 61 74 65 22 3a 22 30 32 2f 30 32 2f 32 30 30 31 22 2c 22 6e 65 78 74 52 65 76 69 65 77 44 61 74 65 22 3a 22 30 33 2f 30 33 2f 32 30 30 31 22 7d 5d

text:
[{"id":1,"title":"title","credits":33,"content":"jtyj","levels":1,"qualificationType":1,"entryRequirements":"jytj","createDate":"02/02/2001","nextReviewDate":"03/03/2001"}]

On UI got the exception : Malformed payload: Unknown code: 0x5b

Can you please have a look and let me know in case I have to do something different ?

**Comment by hverma11** [comment]
Hi noodlefrenzy,

 Hope you are back. Did you get chance to look into the above mentioned issue.

**Comment by mbroadst** [comment]
@noodlefrenzy I think its safe to close this for the moment, I've been using the library with ActiveMQ daily and the migration to node-bl seems to have fixed it.

**Comment by noodlefrenzy** [comment]
Great, thanks!
